# Generated by Django 5.0 on 2024-01-06 07:15

import logging
import os

from django.db import migrations


def create_superuser(apps, schema_editor):
    from users.models import CustomUser as User

    superuser_username = os.environ.get("SUPERUSER_USERNAME", "admin")
    superuser_password = os.environ.get("DJANGO_SUPERUSER_PASSWORD", "password")
    superuser_email = os.environ.get("SUPERUSER_EMAIL", "admin@blap.ai")
    
    # Check if a superuser with a specific username exists
    if not User.objects.filter(username=superuser_username).exists():
        User.objects.create_superuser(
            username=superuser_username,
            password=superuser_password,
            email=superuser_email
        )
        logging.info("Superuser created successfully")
    else:
        logging.info("Superuser already created!")

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_superuser)
    ]
